version: '2'
services:
 jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  links:
    - selhub:hub
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker
  depends_on:
    - selhub

 selhub:
  image: selenium/hub
  ports:
    - 4444:4444

 nodeff:
  image: selenium/node-firefox-debug
  ports:
    - 5900
  links:
   - selhub:hub
  environment:
   - HUB_PORT_4444_TCP_ADDR=hub
  depends_on:
    - selhub

 nodechrome:
  image: selenium/node-chrome-debug
  ports:
    - 5900
  links:
   - selhub:hub
  environment:
   - HUB_PORT_4444_TCP_ADDR=hub
  depends_on:
    - selhub
